apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/ilyaa1/jx-poc-node-server:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/ilyaa1/jx-poc-node-server:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: jx-poc-node-server
        chartPath: charts/jx-poc-node-server
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/ilyaa1/jx-poc-node-server"
          image.tag: "{{.TAG}}"
